const SET_WEATHER = 'SET_WEATHER';
const SET_WEATHER_ERROR = 'SET_WEATHER_ERROR';
const SAVE_RESULT = 'SAVE_RESULT';
const FETCH_RESULTS = 'FETCH_RESULTS';

export { SET_WEATHER, SET_WEATHER_ERROR, SAVE_RESULT, FETCH_RESULTS }