const SET_WEATHER = 'SET_WEATHER';
const SET_WEATHER_ERROR = 'SET_WEATHER_ERROR';
const SAVE_SEARCH = 'SAVE_SEARCH';
const FETCH_SEARCHES = 'FETCH_SEARCHES';
const SET_SEARCH = 'SET_SEARCH';

export { SET_WEATHER, SET_WEATHER_ERROR, SAVE_SEARCH, FETCH_SEARCHES, SET_SEARCH }